name: adjfind
version: '1.0.0'
summary: A C++ program containing specialized path finding algorithms related to adjacency/proximity
description: |
  The command-line tool supports three main modes:
  • Road Segmentation Mode: Determines which service points (e.g., hydrants) are closest to each road segment using network distance, and optionally splits roads into discrete distance categories for service area analysis.
  • Neighboring Points Mode: Identifies the nearest neighboring service points along a road network in each direction, calculating spacing distances between facilities like hydrants for regulatory compliance assessment.
  • Structure Access Mode: Computes shortest unobstructed paths from building corners to road networks, finding the least accessible points on buildings for emergency response planning and fire code compliance.

grade: stable
confinement: strict

parts:
  adjfind:
    plugin: cmake
    source: https://github.com/zwang-geog/AdjFind.git
    source-branch: master
    build-packages:
      - build-essential
      - cmake
      - libgdal-dev
      - libboost-all-dev
      - nlohmann-json3-dev
    stage-packages:
      - libgdal32
      - libnlohmann-json3-3
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/snap/adjfind/current
      - -DCMAKE_POSITION_INDEPENDENT_CODE=ON

apps:
  adjfind:
    command: bin/adjfind
    plugs:
      - home
      - removable-media
