name: Build and Release (Cross-Platform Compatible)

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    # Using older OS versions for better backward compatibility
    # Ubuntu 18.04 → Compatible with Ubuntu 16.04+, Debian 9+, CentOS 7+
    # macOS 12 → Compatible with macOS 10.15+  
    # Windows builds → Built locally with Visual Studio 2022 Community
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-12]
        include:
          - os: ubuntu-18.04
            package_manager: apt
            gdal_version: "auto-detected"
            compatibility_note: "Compatible with Ubuntu 16.04+, Debian 9+, CentOS 7+"
          - os: macos-12
            package_manager: brew
            gdal_version: "auto-detected"
            compatibility_note: "Compatible with macOS 10.15+"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1.13

    - name: Setup C++ compiler
      uses: ms-vscode-actions/vscode-cpptools-actions/actions@v1
      with:
        compiler: gcc
        version: 9

    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-18.04'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgdal-dev libboost-all-dev nlohmann-json3-dev
        echo "Installed GDAL version: $(gdal-config --version)"
        echo "Installed Boost version: $(dpkg -l | grep libboost | head -1)"

    - name: Install dependencies (macOS)
      if: matrix.os == 'macos-12'
      run: |
        brew install gdal boost nlohmann-json
        echo "Installed GDAL version: $(gdal-config --version)"
        echo "Installed Boost version: $(brew list --versions boost | head -1)"

    - name: Create build directory
      run: mkdir build

    - name: Configure with CMake
      run: |
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-static-libgcc -static-libstdc++"

    - name: Build project
      run: |
        cd build
        cmake --build . --config Release --parallel

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: adjfind-${{ matrix.os }}-${{ matrix.compatibility_note }}
        path: build/adjfind*

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          artifacts/adjfind-ubuntu-18.04-Ubuntu 16.04+, Debian 9+, CentOS 7+/adjfind
          artifacts/adjfind-macos-12-macOS 10.15+/adjfind
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
